### ISSUE TITLE
images are broken on the readme

### ISSUE THREAD

**Issue by Aarush-Goyal** [eddiejaoude/jaoudestudios#8]
![image](https://user-images.githubusercontent.com/64161383/103730929-f7f6b380-5009-11eb-912a-584f7df96e4a.png)

**Comment by Utkarsh299-tech** [comment]
Hey, @Aarush-Goyal! I can fix two of the broken images i.e., dependencies Status and devDependencies Status. But I think the image to Agency Preview is not found.

**Comment by Aarush-Goyal** [comment]
@Utkarsh299-tech That would be great!
 @eddiejaoude any idea how can we fix the agency preview as the link is now giving 404 error has the page shifted to another route?

**Comment by eddiejaoude** [comment]
Oh good spot everyone 👍 Thank you for this 🤓 .

I think taking a screenshot of the deployed website http://jaoudestudios.com and dropping it in a comment here, then use the url generated by GitHub as the image source.

**Comment by Utkarsh299-tech** [comment]
Hey @eddiejaoude! How's this screenshot? Can I add this one?
-> Screenshot: 
<img width="947" alt="eddie" src="https://user-images.githubusercontent.com/60184229/103766319-a6b7e580-5044-11eb-8c59-c321f255398c.png">

**Comment by eddiejaoude** [comment]
yep do it 👍 thank you 🤓
